### ISSUE TITLE
rendering doesn't work

### ISSUE THREAD

**Issue by YitzhakSp** [mryellow/gym-mazeexplorer#2]
env.render() doesn't work. is there any way to fix it ?

**Comment by mryellow** [comment]
Details?

Tests are passing on my old local install, haven't looked at this environment for awhile. Possible something has changed upstream.

**Comment by YitzhakSp** [comment]
here's the code
```
import gym_mazeexplorer
import gym
env = gym.make('MazeExplorerEat-v0')
env.reset()
for i in range(10):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
```
it runs but there is no window popping up or so.
my system is:
win10, python 3.6

**Comment by mryellow** [comment]
Do the tests pass?

**Comment by mryellow** [comment]
Tests pass?

`python -m unittest discover`

Seems it prefers being run as `python foo.py` rather than `./foo.py`.

See if you can get MazeExplorer itself `python standalone.py` running.

https://github.com/mryellow/maze_explorer

My readme code is looking for it under an old gym name (without `Eat` part). Now when I've updated to the correct name it just runs then finishes without error.

Okay spotted it.

https://github.com/mryellow/gym-mazeexplorer/blob/39febd7c179130c39c0f8dcecbfe87e986805a8e/gym_mazeexplorer/envs/mazeexplorer_env.py#L18

That `False` "invisible".

Passed to `cocos.director` as `visible` config in maze_exp https://github.com/mryellow/maze_explorer/blob/master/mazeexp/engine/mazeexp.py#L28

**Comment by YitzhakSp** [comment]
nice, now it works !
